export const SrrET_LOGIN_TRUE = 'SET_LOGIN_TRUE';

export const SET_USER = 'SET_USER'
export const UPDATE_USER= 'UPDATE_USER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CONCERN_UPDATE = 'CONCERN_UPDATE';
export const UPDATE_QUOTE_OF_THE_DAY = 'UPDATE_QUOTE_OF_THE_DAY';
